server:
  tomcat:
    max-threads: 500 # Maximum amount of worker threads.
    min-spare-threads: 50 # Minimum amount of worker threads


#监控短点配置
management:
  security:
    enabled: false
  info:
    git:
      mode: full
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false

# ribbon 超时时间
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

# 关闭熔断器超时检测时间功能， 生产环境不建议关闭
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
